version: '3.4'
services:
#  Optional
#  alfresco-totp-authenticator-platform-share:
#    image: ${docker.share.image}:${alfresco.share.version}
#    environment:
#      REPO_HOST: alfresco-totp-authenticator-platform-acs
#      REPO_PORT: 8080
#    ports:
#      - "${share.port}:8080"
  alfresco-totp-authenticator-platform-acs:
    image: alfresco-content-services-alfresco-totp-authenticator-platform:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
#      CATALINA_OPTS: "-XX:HotswapAgent=fatjar -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    command: ["catalina.sh", "run"]
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - alfresco-totp-authenticator-platform-acs-volume:/usr/local/tomcat/alf_data
      - ../../../../alfresco-totp-authenticator-platform/target/classes:/usr/local/tomcat/hotswap-agent/alfresco-totp-authenticator-platform/target/classes
    depends_on:
      - alfresco-totp-authenticator-platform-postgres
  alfresco-totp-authenticator-platform-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - alfresco-totp-authenticator-platform-db-volume:/var/lib/postgresql/data
  alfresco-totp-authenticator-platform-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: alfresco-totp-authenticator-platform-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: alfresco-totp-authenticator-platform-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - alfresco-totp-authenticator-platform-ass-volume:/opt/alfresco-search-services/contentstore
      - alfresco-totp-authenticator-platform-ass-volume:/opt/alfresco-search-services/data
volumes:
  alfresco-totp-authenticator-platform-acs-volume:
    external: true
  alfresco-totp-authenticator-platform-db-volume:
    external: true
  alfresco-totp-authenticator-platform-ass-volume:
    external: true
