name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B -DskipTests clean package

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: alfresco-totp-authenticator-platform.amp
          path: alfresco-totp-authenticator-platform/target/*.amp

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: alfresco-totp-authenticator-share.amp
          path: alfresco-totp-authenticator-share/target/*.amp
