name: Java CD

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Validate version
        run: mvn -B validate

      - name: Deploy to GitHub packages
        # Have to skip doc and sources because GH Packages doesn't support classifiers
        run: mvn -B deploy -Dmaven.javadoc.skip=true -Dmaven.source.skip=true
        env:
          GITHUB_TOKEN: ${{ github.token }}